= DCA0445: Processamento Digital de Imagens =

Efrain Marcelo <efrainmpp@gmail.com>

== Questões Capitulo 5 - Preenchendo regiões ==

=== Exercício 1  ===

Observando-se o programa link:https://agostinhobritojr.github.io/tutorial/pdi/exemplos/labeling.cpp[labeling.cpp] como exemplo, é possível verificar que caso existam mais de 255 objetos na cena, o processo de rotulação poderá ficar comprometido. Identifique a situação em que isso ocorre e proponha uma solução para este problema.

==== Resposta: ====
Se houver mais de 255 objetos na cena, ocorrerá um problema porque o valor máximo que um 
pixel pode ter é 255 (para uma imagem em escala de cinza de 8 bits). Portanto, os objetos 
adicionais não poderão ser rotulados corretamente e sua contagem será limitada a 255.

Uma solução para esse problema é modificar a lógica de rotulação para permitir a 
identificação de mais de 255 objetos. Em vez de usar diretamente o valor do pixel para 
rotulagem, pode-se armazenar um mapa de rótulos separado que atribui um número de rótulo 
exclusivo a cada objeto encontrado.

=== Exercício 2 ===

Aprimore o algoritmo de contagem apresentado para identificar 
regiões com ou sem buracos internos que existam na cena. Assuma 
que objetos com mais de um buraco podem existir. Inclua suporte 
no seu algoritmo para não contar bolhas que tocam as bordas da 
imagem. Não se pode presumir, a priori, que elas tenham buracos 
ou não. 

[source,python]
----	
include::code/chapter_05/aprimorated.py[title="aprimorated.py"]
----